# Generated by Django 5.2.6 on 2025-10-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
